using AcademicAI.Core.Interfaces;
using AcademicAI.Core.Models;

namespace AcademicAI.Detection;

public class AiDetector
{
    private readonly IAgentFactory _agentFactory;
    private readonly IAppSettingsService _settingsService;
    private readonly ISecretStore _secretStore;

    public AiDetector(IAgentFactory agentFactory, IAppSettingsService settingsService, ISecretStore secretStore)
    {
        _agentFactory = agentFactory;
        _settingsService = settingsService;
        _secretStore = secretStore;
    }

    private IAIAgent ResolveAgent()
    {
        var config = _settingsService.GetFeatureDefault("Detector") ?? new FeatureProviderConfig();
        var agent = _agentFactory.GetAgent(config.Provider);
        agent.SetModel(config.Model);
        var apiKey = _secretStore.Load($"apikey_{config.Provider}");
        if (apiKey != null) agent.SetApiKey(apiKey);
        return agent;
    }

    public async Task<DetectionResult> DetectAsync(string text)
    {
        var agent = ResolveAgent();
        var systemPrompt = $"Analyze the following text and determine the probability that it was generated by AI. Respond ONLY with a JSON object in this exact format: {{\"probability\": 0.85, \"reasoning\": \"brief explanation\"}}. Do not include any other text.\n\n{text}";
        var response = await agent.GenerateAsync(systemPrompt);

        try
        {
            var json = response.Trim();
            var start = json.IndexOf('{');
            var end = json.LastIndexOf('}');
            if (start >= 0 && end > start)
            {
                json = json.Substring(start, end - start + 1);
                var doc = System.Text.Json.JsonDocument.Parse(json);
                var probability = doc.RootElement.GetProperty("probability").GetDouble();
                var reasoning = doc.RootElement.TryGetProperty("reasoning", out var r) ? r.GetString() ?? "" : "";
                return new DetectionResult
                {
                    Probability = Math.Clamp(probability, 0, 1),
                    Reasoning = reasoning,
                    RawResponse = response
                };
            }
        }
        catch { }

        return new DetectionResult { Probability = 0, Reasoning = "Could not parse detection result", RawResponse = response };
    }
}

public class DetectionResult
{
    public double Probability { get; set; }
    public string Reasoning { get; set; } = "";
    public string RawResponse { get; set; } = "";
}
