using AcademicAI.Core.Interfaces;
using AcademicAI.Core.Models;

namespace AcademicAI.Humanizer;

public class TextHumanizer
{
    private readonly IAgentFactory _agentFactory;
    private readonly IAppSettingsService _settingsService;
    private readonly ISecretStore _secretStore;

    public TextHumanizer(IAgentFactory agentFactory, IAppSettingsService settingsService, ISecretStore secretStore)
    {
        _agentFactory = agentFactory;
        _settingsService = settingsService;
        _secretStore = secretStore;
    }

    private IAIAgent ResolveAgent()
    {
        var config = _settingsService.GetFeatureDefault("Humanizer") ?? new FeatureProviderConfig();
        var agent = _agentFactory.GetAgent(config.Provider);
        agent.SetModel(config.Model);
        var apiKey = _secretStore.Load($"apikey_{config.Provider}");
        if (apiKey != null) agent.SetApiKey(apiKey);
        return agent;
    }

    public async Task<string> HumanizeAsync(string text, string tone, string strength = "Moderate")
    {
        var agent = ResolveAgent();
        var strengthInstruction = strength switch
        {
            "Subtle" => "Make only minor adjustments to phrasing and word choice.",
            "Aggressive" => "Significantly restructure sentences, add natural imperfections, vary rhythm dramatically, and break overly uniform patterns.",
            _ => "Vary sentence structure, add natural transitions, and avoid overly perfect grammar."
        };

        var toneInstruction = tone switch
        {
            "Academic" => @"Use a scholarly academic tone as if written by a real university student or researcher. Follow these rules strictly:
- Use proper academic vocabulary and discipline-specific terminology naturally
- Vary sentence length: mix shorter punchy statements with longer analytical ones
- Include natural academic hedging (e.g., 'it appears that', 'this suggests', 'arguably')
- Occasionally use first-person where appropriate ('we observe', 'our analysis shows')
- Add subtle imperfections: a slightly wordy phrase here, an informal connector there
- Use passive and active voice naturally (not exclusively passive)
- Reference concepts with natural phrasing, not robotic listing
- Ensure it reads like genuine academic writing, NOT like AI-generated text
- Maintain the factual content and meaning exactly",
            "Formal" => "Use a formal professional tone. Maintain proper grammar and sophisticated vocabulary but ensure it sounds naturally written by a human, not generated by AI.",
            "Semi-Formal" => "Use a semi-formal tone. Mix professional language with natural, approachable phrasing.",
            "Semi-Casual" => "Use a semi-casual tone. Keep it informative but conversational and easy to read.",
            "Casual" => "Use a casual, conversational tone. Make it sound like a real person explaining things naturally.",
            _ => $"Use a {tone} tone."
        };

        var systemPrompt = $@"You are an expert academic text humanizer. Rewrite the following text to make it completely undetectable as AI-generated.

{toneInstruction}

{strengthInstruction}

CRITICAL: Only return the rewritten text. Do not add explanations, notes, or commentary.

TEXT TO HUMANIZE:
{text}";
        return await agent.GenerateAsync(systemPrompt);
    }
}
